### ISSUE TITLE
Proposal for Additional Docker Image Tagging Scheme and Regular Version Updates

### ISSUE THREAD

**Issue by diazoxide** [p2-inc/phasetwo-containers#18]
To enhance the flexibility of the build process for additional projects that extend PhaseTwo Docker images, it would be beneficial to add more tags to these Docker images. For instance, on quai.io, you currently have versions such as `21.1.2.1688664025`. 

I propose the introduction of additional types of tags as follows:
- 21
- 21.1
- 21.1.2
- 21.1.2.1688664025 (existing)

Furthermore, it is crucial to keep these versions updated to the latest version of the current major version for efficiency and compatibility purposes.

<img width="1513" alt="image" src="https://github.com/p2-inc/phasetwo-containers/assets/25997814/8d90e845-e673-4231-8b93-cb09d3ae22ef">

**Comment by xgp** [comment]
Thanks for the suggestion @diazoxide . The job that builds and releases those docker images is here https://github.com/p2-inc/phasetwo-containers/blob/main/.github/workflows/release.yml#L34-L47 Please PR with the changes you're suggesting.

> Furthermore, it is crucial to keep these versions updated to the latest version of the current major version for efficiency and compatibility purposes.

I don't understand this one. Can you be more specific?

**Comment by xgp** [comment]
Got it. If you update the tags section https://github.com/p2-inc/phasetwo-containers/blob/main/.github/workflows/release.yml#L46C1-L48C1 it will clobber the major and minor version on each release.

**Comment by xgp** [comment]
Fixed by #19
