### ISSUE TITLE
Using phasetwo-keycloak:19.0.3-alpha enabling admin console theme phasetwo.v2 causes error for extension organizations

### ISSUE THREAD

**Issue by KDMRyanT** [p2-inc/phasetwo-containers#2]
Hello,
I was pointed at p2inc containers as I was using/building keycloak-orgs into keycloak - this is a way better way to test the extensions!
Anyways, I started docker image phasetwo-keycloak:19.0.3-alpha this morning with the following parameters:

commands/args = start-dev
entrypoint = /opt/keycloak/bin/kc.sh

environment = KEYCLOAK_ADMIN=admin ; KEYCLOAK_ADMIN_PASSWORD=admin ; KC_HOSTNAME=testkeycloak.mykdm.dev.local ; KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/server.keystore ; KC_HTTPS_KEY_STORE_PASSWORD=testing12345 ; 
MAPPINGS/BINDS = /home/rturnbull/important_keycloak_files/server.keystore:/opt/keycloak/conf/server.keystore
Network Mode = mykdm.dev.local 
PortBindings = 8080 to 8080; 8443 to 8443

This is all fine and the container starts properly.  I then start a browser and login to https://testkeycloak.mykdm.dev.local:8443/admin to the administration console.  On the master realm ( as no other realms are started yet ) I go to realm settings->Theme and for admin console them I select phasetwo.v2 and save.  I logout and restart a browser session and login to the console again.  There I now see on the left hand menu "Extensions" and "Organizations".  However this is where it displays an error - see attachment. 

![keycloak-phasetwo-organizations-theme-error](https://user-images.githubusercontent.com/105240774/196467864-771b2cc7-85c1-44f0-810e-9b0bb589b67f.jpg)

The error displayed is "e.map is not a function" and I'm presented with a "Press here to refresh and continue".  I do that and I briefly see a "Organizations" display but then the screen refreshes again and I'm back to the master realm.

Is there anything that I have done in setup that causes this error?  Please advise.

**Comment by xgp** [comment]
fixed
