### ISSUE TITLE
Version 21.1.2.1691149882 don't start with fresh database

### ISSUE THREAD

**Issue by thebestgin** [p2-inc/phasetwo-containers#21]
This container does not start when the database is created from scratch with V21.1.2.1691149882.
Have used the Docker-Compose file in repo.

Errors:
```
keycloak_1  | 2023-08-05 09:16:02,096 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 9f8a583f49d3-28418, Site name: null
keycloak_1  | 2023-08-05 09:16:02,250 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
keycloak_1  | 2023-08-05 09:16:02,333 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
keycloak_1  | 2023-08-05 09:16:03,592 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
keycloak_1  | 2023-08-05 09:16:03,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak_1  | 2023-08-05 09:16:03,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: jakarta/ws/rs/core/UriInfo
keycloak_1  | 2023-08-05 09:16:03,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: jakarta.ws.rs.core.UriInfo
keycloak_1  | 2023-08-05 09:16:03,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
testphase2_keycloak_1 exited with code 1
```

With the older V21.1.2.1688664025 it works.

**Comment by xgp** [comment]
@thebestgin which docker-compose? I can't recreate from the one at root

**Comment by thebestgin** [comment]
The error ources with the following docker-compose.yml.
The following file is different from the specified latest Docker image version and the "entrypoint" part.

[docker-compose.zip](https://github.com/p2-inc/phasetwo-containers/files/12267016/docker-compose.zip)

**Comment by xgp** [comment]
Thanks. Looks like a version incompatibility in the jars built against kc 22, where they switched from javax to jakarta libs. Building a new image now. Deleted the old tags.

**Comment by thebestgin** [comment]
Thanks. The new image works.

**Comment by thebestgin** [comment]
Yes, in KC22 they switched  to jakarta.
What KC Version is behind Phase-Two V21?

> Thanks. Looks like a version incompatibility in the jars built against kc 22, where they switched from javax to jakarta libs. Building a new image now. Deleted the old tags.

Yes, they switched to jakarta in KC22.
But the new Phase Two Image Version is 21, right?

**Comment by xgp** [comment]
https://github.com/p2-inc/phasetwo-containers#versioning
