### ISSUE TITLE
Error when loading webpage with example docker command from README

### ISSUE THREAD

**Issue by vishen** [p2-inc/phasetwo-containers#30]
Hello! 

I'm not sure if I am missing a step, but I tried following the docker command posted in the example, and I am using the most recent version `VERSION=22.0.5`:

```
docker run --name phasetwo_test --rm -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE_PATH=/auth \
    quay.io/phasetwo/phasetwo-keycloak:$VERSION \
    start-dev --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-cache-themes=false
```

And when I go to `http://0.0.0.0:8080` I get 404 and a webpage saying `Resource not found`.  

I'm not sure if there is more that I need to do, but if so it isn't clear to me what I am missing?

**Comment by vishen** [comment]
I am closing this since I figured it out. It is probably obvious to people familiar with Keycloak, but since I am not it took me a little bit to work out. I had to go to `http://0.0.0.0:8080/auth/admin/master/console` to get to the Keycloak admin console.

**Comment by xgp** [comment]
Thanks @vishen for posting your solution, as it may help others who are not familiar with Keycloak.
