### ISSUE TITLE
Can't add a specific organization attribute in access token

### ISSUE THREAD

**Issue by prifulnath** [p2-inc/phasetwo-containers#42]
I have multiple attributes under an organization. I need only two or three in the access token. Is there an option to add a specific Organization attribute to token? Didn't see any specific option in the client scope mapper.

**Comment by xgp** [comment]
No.

Is there such a mapper that is available with Keycloak? E.g. an attribute mapper for Group or Realm Attributes that allows selection by scope? Perhaps you could use that as a basis for an enhancement proposal or PR.

**Comment by prifulnath** [comment]
@xgp we can map specific attribute like **phone_number**, **country_code** to token using User Attribute token mapper for user as below,
![image](https://github.com/p2-inc/phasetwo-containers/assets/15168579/30431c86-b627-4098-8c18-3810c97aad24)

But if we add attribute under organization like below, and if i wanted to add only **attribute1** to token, then there is no option, right?
![image](https://github.com/p2-inc/phasetwo-containers/assets/15168579/5b6e6522-2aab-4f0f-bf96-0e53ba07340a)

It will only allow organization attribute add as a whole.
![image](https://github.com/p2-inc/phasetwo-containers/assets/15168579/5856d4f4-ad61-4d42-af7d-796aa9fb2d93)

**Comment by xgp** [comment]
@prifulnath Thanks for that information. If that's something you need, please PR. My guess is that the User Attribute mapper would serve as a base to make a similar one for organizations. Also, take a look at the https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/protocol/oidc/mappers/OrganizationAttributeMapper.java code, as that is where the organization attribute mapping occurs right now.

**Comment by xgp** [comment]
Also, if you're going to make a PR, please open a ticket in the https://github.com/p2-inc/keycloak-orgs repo instead of here.

**Comment by prifulnath** [comment]
@xgp Sure. Thak you for your help.
