### ISSUE TITLE
Purpose of the default service account org-admin-...@noreply.phasetwo.io

### ISSUE THREAD

**Issue by efleurimond** [p2-inc/phasetwo-containers#48]
Hello,

I discovered these extensions 2 or 3 days ago and I am currently testing them. So far I find them very useful; congratulations to P2.
I have a question though, what is the use of the default user account "org-admin-...@noreply.phasetwo.io". Can it be disabled or deleted?

Thanks in advance.

**Comment by xgp** [comment]
Those are organization "service accounts" that allow the creation of a portal link (see the action menu when you have an organization open in the admin UI). You can delete the default user, but be aware that those links will not work.
