### ISSUE TITLE
Missing environment variable on postgres docker-compose example

### ISSUE THREAD

**Issue by fakegermano** [p2-inc/phasetwo-containers#49]
Hello

I've recently used the `postgres/docker-compose.yml` example and noticed that no communication between the keycloak instance and the database was taking place. After some digging, I've realized that the keycloak instance was using the `dev-file` backing solution instead of `postgres`. 

To remedy this and make the example complete, we should add `KC_DB: postgres` as one of the environment variables on the `keycloak` service on the `docker-compose.yml` file.

**Comment by xgp** [comment]
Thanks. Please PR.

**Comment by fakegermano** [comment]
@xgp thanks! PR sent.
