### ISSUE TITLE
Use of admin-ui as static jar file in docker image. 

### ISSUE THREAD

**Issue by felixminom** [p2-inc/phasetwo-containers#57]
- Hey there 👋🏽 thanks for the work done for adding organizations, it's been helpful. 

I've been working with your repo to install the phase-two orgs extension in my docker image. While working on this I noticed that there are two packages that you're installing directly by copying a `.jar` file into the image, these packages are: 
1. [keycloak-rest-provider-4.0.1-SNAPSHOT.jar](https://github.com/p2-inc/phasetwo-containers/blob/main/libs/ext/keycloak-rest-provider-4.0.1-SNAPSHOT.jar)
2. [phasetwo-admin-ui-25.0.4.jar](https://github.com/p2-inc/phasetwo-containers/blob/main/libs/ext/phasetwo-admin-ui-25.0.4.jar)

I was wondering if there's a plan to move away from this approach especially around the `phasetwo-admin-ui` jar, since the [repo](https://github.com/p2-inc/keycloak-ui) was archived last year. 

Do you have any plans around this? Thank you.

**Comment by xgp** [comment]
The jars you point to are stored in the repository because they are not available in Maven Central. 

The keycloak-rest-provider extension is from this project https://github.com/daniel-frak/keycloak-user-migration

The phasetwo-admin-ui extension is out customized Keycloak admin UI and is not built from the archived repository you mentioned.

**Comment by felixminom** [comment]
Thank you. 

In that case, a better question will be, why not upload those to maven central?

**Comment by xgp** [comment]
The keycloak-rest-provider extension is owned by someone else. You can't upload an artifact to Maven Central with a `groupId` (namespace) that you don't own.

The phasetwo-admin-ui extension is not a general purpose library that would ever be pulled in as a dependency or referenced in a pom. It's exclusively relevant as part of the docker image.
