### ISSUE TITLE
Use tags do differentiate between keycloak versions

### ISSUE THREAD

**Issue by cato447** [p2-inc/phasetwo-containers#8]
Dear p2-inc team,

It would be really helpful to have tags to differentiate between keycloak versions.
I am currently using the commit history of the Dockerfile to get to the last commit regarding a keycloak version.

Thanks for all your work!
It's awesome :)

**Comment by xgp** [comment]
Hi @cato447 Thanks for your feedback! Just to clarify, you want a git tag here to correspond to the Keycloak version? E.g. something like the Docker image tag we use? https://quay.io/repository/phasetwo/phasetwo-keycloak?tab=tags

**Comment by cato447** [comment]
It would be awesome if this would be possible. I am currently writing documentation to add keycloak-orgs functionality to a freshly downloaded keycloak instance for local deployment without docker (my bosses asked me for this because our hoster has no k8/docker support). Do you want the docs for "manual" deployment btw?

**Comment by xgp** [comment]
> It would be awesome if this would be possible

I think it should be fairly easy. We do the docker image build and release on merge to main. We could add a git tag step to this job in the github action we use: https://github.com/p2-inc/phasetwo-containers/blob/main/.github/workflows/release.yml#L9

> Do you want the docs for "manual" deployment btw?

Wait. Is it my birthday? I'd love it if you could share. Either post it here, and I'll add it to the repo, or do a PR (maybe in a `docs/` folder?) and I'll review and merge.

**Comment by cato447** [comment]
Alright will open a PR when I am finished refining the docs

**Comment by xgp** [comment]
added in 6680fd83c8785d084c10a2b9a8f4871443f9e8f9
